#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1
PROG=/usr/sbin/lighttpd

IFACE="wlan0"

amend_iptables_init() {
	iptables -t nat -N CLIENT_TO_INTERNET
	iptables -t nat -A PREROUTING -i ${IFACE} -j CLIENT_TO_INTERNET
	iptables -t filter -I INPUT -i ${IFACE} -p tcp --dport 2060 -j ACCEPT
	iptables -t filter -I INPUT -i ${IFACE} -p tcp --dport 2061 -j ACCEPT

	iptables -t nat -N HOST_REDIRLIST
	iptables -t nat -A CLIENT_TO_INTERNET -p tcp -i ${IFACE} --dport 80 -j HOST_REDIRLIST
	iptables -t nat -A CLIENT_TO_INTERNET -p tcp -i ${IFACE} --dport 443 -j HOST_REDIRLIST

	iptables -t nat -A CLIENT_TO_INTERNET -p tcp --dport 80 -j REDIRECT --to-ports 2060

	iptables -w -t filter -I FORWARD 1 -p udp -i ${IFACE} --dport 53 -j ACCEPT
	iptables -w -t filter -I FORWARD 2 -i ${IFACE} -m mark --mark 0xfb -j ACCEPT
	iptables -w -t filter -A FORWARD -i ${IFACE} -j DROP
}

start_service() {
        user_exists http || user_add http
        [ -d /var/log/lighttpd ] || {
                mkdir -m 0775 -p /var/log/lighttpd
                chgrp www-data /var/log/lighttpd
        }
	
	amend_iptables_init

        procd_open_instance
        procd_set_param command $PROG -D -f /etc/lighttpd/swf_redirect.conf
        procd_close_instance
}
