#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1
PROG=/usr/sbin/lighttpd

start_service() {
        user_exists http || user_add http
        [ -d /var/log/lighttpd ] || {
                mkdir -m 0775 -p /var/log/lighttpd
                chgrp www-data /var/log/lighttpd
        }

set -x
        procd_open_instance
set +x
        procd_set_param command $PROG -D -f /etc/lighttpd/swf_redirect.conf
        procd_close_instance
}
