#!/usr/bin/lua
require("uci")

state = uci.cursor(nil, "/var/state")

print("Status: 302")
print("Location: "..state:get("swf", "main", "landing_page_url"))

print ('\n')

method = os.getenv("REQUEST_METHOD")
if method == 'GET' then
	print(method)
elseif method == 'POST' then
	print(method)
end
