#!/usr/bin/lua
require "luci.cacheloader"
require "luci.sgi.cgi"
json = require("cjson")

response = { api_version = "2.0", token = nil }

print("Content-type: application/json; charset=utf-8")

function getClientToken(client_ip)
	--print(client_ip)
	return nil
end

function getGatewayId()
	return 'todo1gwid'
end

response.token = getClientToken(os.getenv("REMOTE_ADDR"))
response.gateway_id = getGatewayId()

print( json.encode(response) )
