#!/bin/sh

uci -q batch <<-EOF
	delete firewall.fbwifi
	set firewall.fbwifi.enabled=0
	set firewall.fbwifi.family=ipv4
	set firewall.fbwifi=include
	set firewall.fbwifi.path=/usr/share/fbwifi/firewall.include
	set firewall.fbwifi.reload=1
	set firewall.fbwifi.type=script
	commit firewall
EOF

exit 0
