#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1
PROG=/usr/sbin/lighttpd

IFACE="br-lan"

amend_iptables_init() {
	# create and set up redirection chains
	iptables -w -t nat -N CLIENT_TO_INTERNET
	iptables -w -t nat -A PREROUTING -i "$IFACE" -j CLIENT_TO_INTERNET
	iptables -w -t nat -A CLIENT_TO_INTERNET -p tcp -i "$IFACE" --dport 80 -m mark --mark 0xfb -j ACCEPT
	iptables -w -t nat -A CLIENT_TO_INTERNET -p tcp -i "$IFACE" --dport 80 -j REDIRECT --to-ports "$http_port"
	iptables -w -t nat -A CLIENT_TO_INTERNET -p tcp -i "$IFACE" --dport 443 -m mark --mark 0xfb -j ACCEPT

	# Accept redirected traffic
	iptables -w -t filter -I INPUT 1 -i "$IFACE" -p tcp --dport "$http_port" -j ACCEPT
	iptables -w -t filter -I INPUT 1 -i "$IFACE" -p tcp --dport "$https_port" -j ACCEPT

	# create and prepend marking chains (add/del user scpripts use this chain)
	iptables -w -t mangle -N CLIENT_TO_INTERNET
	iptables -w -t mangle -I PREROUTING 1 -i "$IFACE" -j CLIENT_TO_INTERNET

	# v2.0 redirection
	iptables -w -t nat -N HOST_REDIRLIST
	iptables -w -t nat -I CLIENT_TO_INTERNET 1 -p tcp -i "$IFACE" --dport 80 -j HOST_REDIRLIST
	iptables -w -t nat -I CLIENT_TO_INTERNET 2 -p tcp -i "$IFACE" --dport 443 -j HOST_REDIRLIST

	iptables -w -t mangle -N TRAFFIC_ALLOWLIST
	iptables -w -t mangle -I PREROUTING 2 -i "$IFACE" -j TRAFFIC_ALLOWLIST

	iptables -w -t filter -I FORWARD 1 -p udp -i "$IFACE" --dport 53 -j ACCEPT
	iptables -w -t filter -I FORWARD 2 -i "$IFACE" -m mark --mark 0xfb -j ACCEPT
	iptables -w -t filter -A FORWARD -i "$IFACE" -j DROP
}

generate_lighttpd_config() {

	config_load fbwifi
	config_get login_url 'main' 'captive_portal_url'

	cat << EOF > /var/run/fbwifi_redirect.conf
server.port = $http_port
server.document-root = "/tmp"
server.modules += ( "mod_redirect" )
server.modules += ( "mod_openssl" )

\$SERVER["socket"] == ":$https_port" {
    ssl.engine = "enable"
    ssl.pemfile = "/etc/fbwifi/https_server_cert"
    ssl.privkey = "/etc/fbwifi/https_server_key"
}

url.redirect = ("" => "${login_url}")
url.redirect-code = 302
EOF

}

update_crontab() {
	WIP=$( mktemp )
	crontab -l > ${WIP}
	grep -q "fbwifi_validate_token_db" ${WIP} && return

	echo '*/5 * * * * /usr/sbin/fbwifi_validate_token_db' >> ${WIP}
	crontab ${WIP}
	/etc/init.d/cron restart
}

start_service() {

	config_load fbwifi
	config_get_bool enabled 'main' 'enabled' '0'
	[ "$enabled" -eq 0 ] && return

	config_get http_port main http_port
	[ -z "$http_port" ] && {
		logger -t fbwifi "required option http_port not set"
		exit 1
	}

	config_get https_port main https_port
	[ -z "$https_port" ] && {
		logger -t fbwifi "required option https_port not set"
		exit 1
	}

	logger "[fbwifi] Enabled; starting"
	
	mkdir -p /etc/fbwifi

        user_exists http || user_add http
        [ -d /var/log/lighttpd ] || {
                mkdir -m 0775 -p /var/log/lighttpd
                chgrp www-data /var/log/lighttpd
        }

	update_crontab

	/etc/init.d/firewall restart
	amend_iptables_init

	/usr/sbin/fbwifi_get_config
	
	/etc/init.d/lighttpd reload
	generate_lighttpd_config
        procd_open_instance
        procd_set_param command $PROG -D -f /etc/lighttpd/fbwifi_redirect.conf
        procd_close_instance
}
