#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1

update_crontab() {
	WIP=$( mktemp )
	crontab -l > ${WIP}
	grep -q "fbwifi_validate_token_db" ${WIP} && return

	echo '*/5 * * * * /usr/sbin/fbwifi_validate_token_db' >> ${WIP}
	crontab ${WIP}
	/etc/init.d/cron restart
}

reload_service() {
	restart
}

service_triggers() {
	procd_add_reload_trigger fbwifi
}

start_service() {

	config_load fbwifi
	config_get_bool enabled 'main' 'enabled' '0'
	[ "$enabled" -eq 0 ] && return

	config_get http_port main http_port
	[ -z "$http_port" ] && {
		logger -t fbwifi "required option http_port not set"
		exit 1
	}

	config_get https_port main https_port
	[ -z "$https_port" ] && {
		logger -t fbwifi "required option https_port not set"
		exit 1
	}

	logger "[fbwifi] Enabled; starting"

	mkdir -p /tmp/fbwifi

	update_crontab

	/usr/sbin/fbwifi_get_config

	login_url=$(uci -p /var/state get fbwifi.main.captive_portal_url)
	[ -z "$login_url" ] && {
		logger -t fbwifi "captive_portal_url not available yet"
		exit 1
	}
	printf '{ "request": [ ["redirect", "%s", 302] ] }' "$login_url" > /tmp/fbwifi/uhttpd-redirect.json

	/etc/init.d/uhttpd restart
}
