#!/usr/bin/lua
http = require("ssl.https")
json = require("cjson")

GATEWAY_TOKEN = require("swf_gateway_token")

URL="https://api.fbwifi.com/v2.0/gateway"
body, code, headers = http.request(URL.."?access_token="..GATEWAY_TOKEN.."&fields=config,config_version")
--print(code)
--print(headers)
--for key,value in pairs(headers) do
--	print(key.." "..value)
--end
--print(body)

obj = json.decode(body)
--table.foreach(obj, print)
--table.foreach(obj['config'], print)

function save_cert(name, value)
	local f = assert(io.open("/etc/swf/"..name, "w"))
	f:write(value)
	f:close()
end

function process_redirect(ix, ip)
	print("TODO: redirect ip("..ip..") -> runtime")
end

save_cert("https_server_cert", obj['config']['https_server_cert'])
save_cert("https_server_key", obj['config']['https_server_key'])

table.foreach(obj['config']['host_redirect_ips'], process_redirect)

function process_traffic_rule(ix, ip)
	print("TODO: traffic_rule("..tostring(ip)..") -> runtime")
end

function process_cross_origin_rule(ix, ip)
	print("TODO: cross_origin_rule("..tostring(ip)..") -> runtime")
end

function process_url(ix, ip)
	print("TODO: URL_rule("..tostring(ip)..") -> runtime")
end


table.foreach(obj['config']['traffic_allowlist'], process_traffic_rule)
table.foreach(obj['config']['cross_origin_allowlist'], process_cross_origin_rule)
table.foreach(obj['config']['urls'], process_url)

