#!/usr/bin/lua
http = require("ssl.https")
json = require("cjson")
require("uci")
log = require("posix.syslog")

GATEWAY_TOKEN = require("swf_gateway_token")

state = uci.cursor(nil, "/var/state")

URL="https://api.fbwifi.com/v2.0/gateway"
body, code, headers = http.request(URL.."?access_token="..GATEWAY_TOKEN.."&fields=config,config_version")

obj = json.decode(body)

function save_cert(name, value)
	log.syslog(log.LOG_INFO, "[swf] Saving cert "..name)
	local f = assert(io.open("/etc/swf/"..name, "w"))
	f:write(value)
	f:close()
end

function process_redirect(ix, ip)
	log.syslog(log.LOG_INFO, "[swf] Redirect "..ip)
	print("TODO: redirect ip("..ip..") -> runtime")
end

save_cert("https_server_cert", obj['config']['https_server_cert'])
save_cert("https_server_key", obj['config']['https_server_key'])

table.foreach(obj['config']['host_redirect_ips'], process_redirect)

function process_traffic_rule(ix, ip)
	log.syslog(log.LOG_INFO, "[swf] Traffic rule "..ix)
	print("\nTODO: traffic_rule("..tostring(ix)..", "..tostring(ip)..") -> runtime")
	table.foreach(ip, print)
end

function process_cross_origin_rule(ix, ip)
	log.syslog(log.LOG_INFO, "[swf] Cross origin rule "..ip)
	print("TODO: cross_origin_rule("..tostring(ix)..", "..tostring(ip)..") -> runtime")
end

function process_url(url_purpose, fqdn)
	log.syslog(log.LOG_INFO, "[swf] Caching "..url_purpose)
	state:set("swf", "main", url_purpose, fqdn)	
end

state:set("swf", "main", "config")

table.foreach(obj['config']['traffic_allowlist'], process_traffic_rule)
table.foreach(obj['config']['cross_origin_allowlist'], process_cross_origin_rule)
table.foreach(obj['config']['urls'], process_url)

state:save('swf')
