#!/usr/bin/lua

http = require("ssl.https")
json = require("cjson")
log = require("posix.syslog")
swf = require("swf")

response = { valid = false }

response.valid = swf.validate_token(arg[1])

print( json.encode(response) )
